@startuml
title Диаграмма контекста Тёплый дом

top to bottom direction

!include C4_Context.puml

Person(user, "Пользователь", "Пользователь системы")

System(WarmHouseSystem, "Система Тёплый дом", "Система управления устройствами")

Rel(user, WarmHouseSystem, "Добавляет устройства, настраивает сценарии, пользуется системой, просматривает телеметрию")

@enduml