@startuml
title Диаграмма контейнеров Тёплый дом

top to bottom direction

!include C4_Container.puml

Person(user, "Пользователь", "Пользователь системы")

System(WarmHouseSystem, "Система Тёплый дом", "Система управления устройствами")

Container_Boundary(WarmHouseSystem, "Система Тёплый дом") {
  Container(ApiGateway, "API Gateway", "", "Маршрутизирует трафик между микросервисами")
  Container(AuthenticationService, "Служба аутентификации", "Java", "Обрабатывает запросы авторизации")
  Container(DeviceManagementService, "Служба управления устройствами", "Java", "Управляет умными устройствами")
  Container(DeviceMonitoringService, "Служба мониторинга", "Java", "Мониторинг состояния устройств")
  Container(AuthenticationDatabase, "База данных", "PostgreSQL", "Хранит все данные аутентификации")
  Container(DeviceDatabase, "База данных", "PostgreSQL", "Хранит все данные устройств")
  Container(KafkaDeviceManagement, "Kafka", "", "Топик управления устройствами")
  Container(KafkaMonitoring, "Kafka", "", "Топик мониторинга")
  Container(Device, "Устройство", "Умное устройство")
}

Rel(user, ApiGateway, "Добавляет устройства, настраивает сценарии, пользуется системой, просматривает телеметрию")
Rel(ApiGateway, AuthenticationService, "Обрабатывает запросы аутентификации")
Rel(ApiGateway, DeviceManagementService, "Управляет умными устройствами")
Rel(ApiGateway, DeviceMonitoringService, "Мониторинг состояния устройств")
Rel(AuthenticationService, AuthenticationDatabase, "Запросы к БД на чтение")
Rel(DeviceManagementService, DeviceDatabase, "Запросы к БД на чтение/запись")
Rel(DeviceManagementService, KafkaDeviceManagement, "Асинхронные запросы на управление устройствами")
Rel(DeviceMonitoringService, KafkaMonitoring, "Читает актуальные состояния устройств")
Rel(Device, KafkaDeviceManagement, "Читает запросы на управление")
Rel(Device, KafkaMonitoring, "Записывает актуальное состояние при изменении")

@enduml